// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService owns the currently open project and drives opening, saving,
 * and closing it, including the native file dialogs involved.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

/**
 * CloseProject closes the current project, replacing it with a blank one.
 */
export function CloseProject(): $CancellablePromise<void> {
    return $Call.ByID(3982222510);
}

export function GetProject(): $CancellablePromise<project$0.Project | null> {
    return $Call.ByID(3013232354);
}

/**
 * GetProjectPath returns the path of the current project's file, or an empty
 * string if it has never been saved.
 */
export function GetProjectPath(): $CancellablePromise<string> {
    return $Call.ByID(4124756129);
}

/**
 * OpenProject prompts the user to pick a project file, loads it and makes it
 * the current project. Returns nil, nil if the user cancels the dialog.
 */
export function OpenProject(): $CancellablePromise<project$0.Project | null> {
    return $Call.ByID(2802521200);
}

/**
 * SaveProject saves the current project to disk, prompting for a location
 * via SaveProjectAs if it doesn't have one yet.
 */
export function SaveProject(): $CancellablePromise<void> {
    return $Call.ByID(41248683);
}

/**
 * SaveProjectAs prompts the user for a location and saves the current project
 * there, making it the project's file going forward. No-ops if the user
 * cancels the dialog.
 */
export function SaveProjectAs(): $CancellablePromise<void> {
    return $Call.ByID(1350620631);
}

/**
 * Called from the UI to update te project object.
 */
export function Update(source: project$0.Project | null): $CancellablePromise<void> {
    return $Call.ByID(1172143294, source);
}
