// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Lexicon {
    "entries": LexiconEntry[] | null;
}

/**
 * Lexicon entry defines a word, its meanings and other data
 */
export interface LexiconEntry {
    /**
     * ID of the word
     */
    "id": string;

    /**
     * the headword (usually in english)
     */
    "headword": string;

    /**
     * one equivalent for now
     */
    "equivalent": string;

    /**
     * tag list
     */
    "tags": string[] | null;

    /**
     * part of speech
     */
    "pos": string;
}
