// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lexicon$0 from "../lexicon/models.js";

/**
 * Project type, contains all the data edited by the user and allows opening/saving/closing.
 */
export interface Project {
    "lexicon": lexicon$0.Lexicon | null;
}
